# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e221c742866be32669280edadc42e376075af78a4ff5d81bec4626e71614ea40821b383aef30cf4b965830450169fefb5ab44c74502ea83dfe74f50f613f7ed5

test:
  secret_key_base: e6653045e08ff75acb83fdc151d1d2adc6cd4aa85ce56bdc739c6da23ea2de4903c6bd81f73821413d27343f7791639f6ee85c71be0909a174cd41deb404ea03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
